---
ynab:
  access_token: # Your YNAB access token
  budget_id: # the first hash in the url when you open your budget
  cash_account_id:  # if set that it creates transactions
                            # to your cash account if withdrawal is detected
accounts:
  - dumper: :fints
    iban: # iban of your account
    ynab_id: # last hash in the url when you click on the account in YNAB
    username: # online banking username / alias
    password: # online banking PIN (NOT! the pin of your bank card!)
    fints_blz: # Your bank's code / Bankleitzahl
    fints_endpoint: # more info can be found here: https://github.com/schurig/ynab-bank-importer/wiki/FinTS---HBCI#fints_endpoint
  - dumper: :n26
    iban: # n26 iban
    ynab_id: # last hash in the url when you click on the account in YNAB
    username: # n26 username
    password: # n26 password
    skip_pending_transactions: false # default: false, only imports transactions when they're processed
    set_category: false # default: false, sets the N26 category name as category
replacements:
  - payee: "NETFLIX INTERNATIONAL B.V."
    replacement: "Netflix"